version: "3.8"

services:
  #service:
  #  container_name: service
  #  image: service
  #  ports:
  #    - "8082:8082"
  #  build: .
  #  working_dir: /app
  #  volumes:
  #    - ./:/app
  #  depends_on:
  #    - keycloak

  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak_db
    ports:
      - "5431:5431"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_user
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"